import path from 'node:path';
import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

// Free of 'electron' too: whoever needs process.execPath / pid receives it as a parameter, so
// the tests run in plain Node.

export function buildInstallerArgs(installDir) {
  const args = ['/S'];
  // NSIS: /D= must be the last parameter and must NOT be quoted, spaces are fine.
  if (installDir) args.push(`/D=${installDir}`);
  return args;
}

export function helperPath(scratchRoot) {
  return path.join(scratchRoot, 'sapphire-update', 'apply-update.cjs');
}

// The helper is GENERATED, so it must be written to disk before anything runs it. This was once
// missed: runUpdateHelper spawns the helper path with nothing writing it, so Electron runs
// as Node with a path that does not exist and exits instantly — and because stdio is deliberately
// ignored, the symptom is just "app closes, version does not change".
export function writeHelper(scratchRoot) {
  const helper = helperPath(scratchRoot);
  mkdirSync(path.dirname(helper), { recursive: true });
  writeFileSync(helper, buildHelperSource(), 'utf8');
  return helper;
}

// The helper is run by Electron ITSELF with ELECTRON_RUN_AS_NODE=1 — so it needs no
// Node/python/other runtime on the user's machine, and does not go through cmd.exe (which causes quoting problems).
export function buildHelperSource() {
  return `// Generated by Sapphire. Node builtins only.
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const [installer, installDir, exePath, parentPidRaw, dryRun] = process.argv.slice(2);
const parentPid = Number(parentPidRaw);
const logPath = path.join(path.dirname(installer), 'update.log');
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const log = (message) => {
  try { fs.appendFileSync(logPath, new Date().toISOString() + ' ' + message + '\\n'); } catch {}
};

(async () => {
  log('helper start pid=' + process.pid + ' waiting for ' + parentPid + ' dryRun=' + dryRun);
  // The installer cannot overwrite Sapphire.exe while the app is running, so wait for the app to
  // really be gone.
  for (let attempt = 0; attempt < 120; attempt += 1) {
    try { process.kill(parentPid, 0); } catch { break; }
    await sleep(500);
  }
  log('parent gone, installing');

  if (dryRun === 'true') {
    log('dry run: not running the installer');
    fs.writeFileSync(path.join(path.dirname(installer), 'dry-run-marker.txt'), 'helper ran\\n');
    return;
  }

  const args = ['/S'];
  if (installDir) args.push('/D=' + installDir);
  const child = spawn(installer, args, { stdio: 'ignore' });
  const exitCode = await new Promise((resolve) => child.on('exit', (code) => { log('installer exit ' + code); resolve(code); }));

  // The installer has been used. This file used to be left behind: 100 MB per version, piling up in
  // temp and never opened again. It is removed only when the install SUCCEEDED — after a failure it
  // is the only way to retry without downloading again.
  if (exitCode === 0) {
    try { fs.rmSync(installer, { force: true }); log('removed installer'); }
    catch (error) { log('could not remove installer: ' + error.message); }
  }

  if (fs.existsSync(exePath)) {
    log('relaunching ' + exePath);
    // ELECTRON_RUN_AS_NODE has to be DROPPED before launching the app, and this is not theoretical
    // caution: this helper runs WITH that variable set to 1, the child process inherits the whole
    // environment, so Sapphire comes up as plain Node with no script — exits immediately with no
    // window and no message. The symptom: the update finishes, the version on disk is new, and the
    // app never appears again. Proven by spawning twice, differing only in this variable:
    // 0 processes vs 4 processes.
    const cleanEnv = Object.assign({}, process.env);
    delete cleanEnv.ELECTRON_RUN_AS_NODE;
    spawn(exePath, [], { detached: true, stdio: 'ignore', env: cleanEnv }).unref();
  } else {
    log('exe missing after install: ' + exePath);
  }
})().catch((error) => log('helper failed: ' + (error && error.stack)));
`;
}

/**
 * Run the helper then exit the app. The caller is responsible for calling app.quit().
 */
export function runUpdateHelper({ scratchRoot, installerPath: installer, installDir, exePath, pid, electronPath, dryRun = false }) {
  const helper = writeHelper(scratchRoot);
  // ELECTRON_RUN_AS_NODE: the already-installed Electron binary runs as plain Node.
  const child = spawn(electronPath, [
    helper, installer, installDir ?? '', exePath, String(pid), String(dryRun)
  ], {
    detached: true,
    stdio: 'ignore',
    env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' }
  });
  child.unref();
  return child.pid;
}